export const genresUtil = [
    "Roguelike action",
    "Arcade and rhythm",
    "First person shooting",
    "Third person shooting",
    "Fighting and martial arts",
    "Street fights",
    "Platform and brokers",
    "Adventure and casual",
    "Adventure",
    "Good plot",
    "Casual",
    "Metroidvania",
    "Visual novel",
    "Puzzles",
    "Adventure role",
    "In a group",
    "Role strategy",
    "By turns",
    "Roguelike",
    "Action role",
    "Adventure role",
    "Japanese role",
    "Simulation",
    "Agriculture and crafts",
    "Quotes",
    "Construction and automation",
    "Living and immersive",
    "Space and flight",
    "Business and tycoons",
    "Sandbox and physics",
    "Cards and table",
    "Cities and colonization",
    "Tower defense",
    "Real time strategy",
    "Turn-based strategy",
    "Grand strategy and 4X",
    "Military",
    "Sports and racing",
    "Careers",
    "team sports",
    "individual sports",
    "Fishing and hunting",
    "Racing simulator",
    "Sports simulator",
    "All the sports",
]